### ISSUE TITLE
Extracting JwtHeaders not working

### ISSUE THREAD

**Issue by wirtsi** [team-carepay/traefik-jwt-plugin#15]
Heya ...

I am trying to extract claims from the token ... but can't seem to get it to work. I am using traefik 2.6.3 and 0.0.6 of this plugin

Config is
```
experimental:
  plugins:
    jwt:
      moduleName: github.com/team-carepay/traefik-jwt-plugin
      version: v0.0.6
```
and

```
http:
  middlewares:
    authorize:
      forwardAuth:
        address: http://localhost:4180
        authResponseHeadersRegex: "(.*)"
    extractJwt:
      plugin:
        jwt:
          Required: true
          PayloadFields:
            - customerId
          JwtHeaders:
            X-Subject: customerId
```

When changing the PayloadFields to eg. - fooCustomerId, then traefik complains about the field not being present in the payload (so the actual decoding of the token works)

What doesn't work is getting the X-Subject to be present. I am sending requests through traefik into httpbin, the extracted headers don't make it into the latter. To be precise, I would expect X-Subject to be filled with the customerId claim

When bumping the version to 0.0.9 I get a panic
```

ERRO[2022-05-03T14:01:12+02:00] Recovered from panic in HTTP handler [127.0.0.1:55115 - /headers]: interface conversion: interface {} is interp.valueInterface, not string  middlewareName=traefik-internal-recovery middlewareType=Recovery
ERRO[2022-05-03T14:01:12+02:00] Stack: goroutine 167 [running]:
github.com/traefik/traefik/v2/pkg/middlewares/recovery.recoverFunc({0x111e18220, 0x1400011c058}, 0x14001208600)
	github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:46 +0x204
panic({0x107bf69e0, 0x1400126c550})
	runtime/panic.go:838 +0x204
github.com/traefik/yaegi/interp.runCfg.func1()
	github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x13c
panic({0x107bf69e0, 0x1400126c550})
	runtime/panic.go:838 +0x204
github.com/traefik/yaegi/interp.runCfg.func1()
	github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x13c
panic({0x107bf69e0, 0x1400126c550})
	runtime/panic.go:838 +0x204
github.com/traefik/yaegi/interp.runCfg.func1()
	github.com/traefik/yaegi@v0.11.2/interp/run.go:193 +0x13c
panic({0x107bf69e0, 0x1400126c550})
	runtime/panic.go:838 +0x204
github.com/traefik/yaegi/interp.typeAssert.func3(0x1400122c4d0)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:441 +0x534
github.com/traefik/yaegi/interp.runCfg(0x14000dda120, 0x1400122c4d0, 0x14001265588?, 0x1083294c0?)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x21c
github.com/traefik/yaegi/interp.call.func9(0x1400122c370)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:1422 +0x7b4
github.com/traefik/yaegi/interp.runCfg(0x14000dd6360, 0x1400122c370, 0x0?, 0x1083294c0?)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x21c
github.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0x14000ee0e40, 0x2, 0x4?})
	github.com/traefik/yaegi@v0.11.2/interp/run.go:1023 +0x3a8
github.com/traefik/yaegi/stdlib._net_http_Handler.ServeHTTP(...)
	github.com/traefik/yaegi@v0.11.2/stdlib/go1_17_net_http.go:288
github.com/traefik/traefik/v2/pkg/middlewares/auth.(*forwardAuth).ServeHTTP(0x14001187cc0, {0x111e18220, 0x1400011c058}, 0x14001208700)
	github.com/traefik/traefik/v2/pkg/middlewares/auth/forward.go:198 +0xbe8
github.com/traefik/traefik/v2/pkg/middlewares/connectionheader.Remover.func1({0x111e18220, 0x1400011c058}, 0x14001208700)
	github.com/traefik/traefik/v2/pkg/middlewares/connectionheader/connectionheader.go:34 +0x23c
net/http.HandlerFunc.ServeHTTP(0x140012662a8?, {0x111e18220?, 0x1400011c058?}, 0x0?)
	net/http/server.go:2084 +0x3c
reflect.Value.call({0x107e54480?, 0x140011a6bb0?, 0x140012669d8?}, {0x106f85f65, 0x4}, {0x14000ee0a20, 0x2, 0x104d3848c?})
	reflect/value.go:556 +0x5e4
reflect.Value.Call({0x107e54480?, 0x140011a6bb0?, 0x14001266a08?}, {0x14000ee0a20, 0x2, 0x2})
	reflect/value.go:339 +0x98
github.com/traefik/yaegi/interp.callBin.func1({0x107e54480?, 0x140011a6bb0?, 0x14001266a98?}, {0x14000ee0a20?, 0x140000b7800?, 0x14000f01440?})
	github.com/traefik/yaegi@v0.11.2/interp/run.go:1472 +0x2c
github.com/traefik/yaegi/interp.callBin.func10(0x1400122c210)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:1646 +0x134
github.com/traefik/yaegi/interp.runCfg(0x1400079ad80, 0x1400122c210, 0x0?, 0x1083294c0?)
	github.com/traefik/yaegi@v0.11.2/interp/run.go:201 +0x21c
github.com/traefik/yaegi/interp.genFunctionWrapper.func2.1({0x14000ee0870, 0x2, 0x4?})
	github.com/traefik/yaegi@v0.11.2/interp/run.go:1023 +0x3a8
net/http.HandlerFunc.ServeHTTP(0x107bedfa0?, {0x111e18220?, 0x1400011c058?}, 0x14000ee0810?)
	net/http/server.go:2084 +0x3c
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x14000f01500, {0x111e18220, 0x1400011c058}, 0x107d9aec0?)
	github.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:29 +0x124
github.com/gorilla/mux.(*Router).ServeHTTP(0x1400119e060, {0x111e18220, 0x1400011c058}, 0x14001208600)
	github.com/gorilla/mux@v1.8.0/mux.go:141 +0x1e8
github.com/traefik/traefik/v2/pkg/middlewares/recovery.(*recovery).ServeHTTP(0x91a22326606?, {0x111e18220?, 0x1400011c058?}, 0x111e18220?)
	github.com/traefik/traefik/v2/pkg/middlewares/recovery/recovery.go:32 +0x70
github.com/traefik/traefik/v2/pkg/middlewares/accesslog.(*FieldHandler).ServeHTTP(0x140011ca940, {0x111e18220, 0x1400011c058}, 0x140011da460?)
	github.com/traefik/traefik/v2/pkg/middlewares/accesslog/field_middleware.go:29 +0x124
github.com/traefik/traefik/v2/pkg/middlewares/metrics.(*metricsMiddleware).ServeHTTP(0x140011e67e0, {0x10846a188?, 0x1400011c040}, 0x14001208600)
	github.com/traefik/traefik/v2/pkg/middlewares/metrics/metrics.go:121 +0x5f8
github.com/traefik/traefik/v2/pkg/middlewares/snicheck.SNICheck.ServeHTTP({{0x1084452b8?, 0x140011e67e0?}, 0x14000edd020?}, {0x10846a188, 0x1400011c040}, 0x14001208600)
	github.com/traefik/traefik/v2/pkg/middlewares/snicheck/snicheck.go:49 +0x114
github.com/traefik/traefik/v2/pkg/middlewares.(*HTTPHandlerSwitcher).ServeHTTP(0x90?, {0x10846a188, 0x1400011c040}, 0x10843d5f0?)
	github.com/traefik/traefik/v2/pkg/middlewares/handler_switcher.go:23 +0x64
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.(*RequestDecorator).ServeHTTP(0x14000011458, {0x10846a188, 0x1400011c040}, 0x14001208500, 0x14000697bd0)
	github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:47 +0x508
github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator.WrapHandler.func1.1({0x10846a188?, 0x1400011c040?}, 0x140007107e0?)
	github.com/traefik/traefik/v2/pkg/middlewares/requestdecorator/request_decorator.go:84 +0x68
net/http.HandlerFunc.ServeHTTP(0x1400087eeb0?, {0x10846a188?, 0x1400011c040?}, 0x9?)
	net/http/server.go:2084 +0x3c
github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders.(*XForwarded).ServeHTTP(0x1400087eeb0, {0x10846a188, 0x1400011c040}, 0x14001208500)
	github.com/traefik/traefik/v2/pkg/middlewares/forwardedheaders/forwarded_header.go:189 +0xd8
net/http.serverHandler.ServeHTTP({0x140001b2008?}, {0x10846a188, 0x1400011c040}, 0x14001208500)
	net/http/server.go:2916 +0x3fc
net/http.initALPNRequest.ServeHTTP({{0x10846b908?, 0x140008bb800?}, 0x1400057e380?, {0x14000134700?}}, {0x10846a188, 0x1400011c040}, 0x14001208500)
	net/http/server.go:3523 +0x1f8
net/http.(*http2serverConn).runHandler(0x0?, 0x104cfaf54?, 0x1400057c180?, 0x0?)
	net/http/h2_bundle.go:5903 +0x74
created by net/http.(*http2serverConn).processHeaders
	net/http/h2_bundle.go:5633 +0x514  middlewareName=traefik-internal-recovery middlewareType=Recovery

```

Thanks in advance

wirtsi

**Comment by blagerweij** [comment]
@wirtsi please check out v0.0.10, it contains a fix for the issue you reported.

**Comment by wirtsi** [comment]
Almost, but still no cake ;-) Thank you so much for this!

For a field that is an integer, there seems to be some kind of casting happening

Eg. jwt has this claim

  "customerId": 2292647,

Which gets parsed into 
    "X-Subject": "2.292647e+06"

String based fields appear to work fine

**Comment by blagerweij** [comment]
Thanks for the report. Please check https://github.com/team-carepay/traefik-jwt-plugin/pull/18

I'll release a new version in a few minutes....
